# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'firebaseTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for firebaseTest
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  target 'firebaseTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'firebaseTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
